"""
Key Signal model for automatic alerts and signals (Section 3.6).
"""
from datetime import datetime
import enum
from uuid import uuid4

from sqlalchemy import Column, DateTime, Enum, ForeignKey, String, Text, JSON, Index, Boolean
from sqlalchemy.orm import relationship

from app.database import Base


class SignalType(str, enum.Enum):
    """Type of signal."""
    RISK = "risk"  # Risk signals (e.g., "Rep late to appointment")
    OPPORTUNITY = "opportunity"  # Opportunity signals (e.g., "High likelihood of closing")
    COACHING = "coaching"  # Coaching signals (e.g., "Missed SOP stage")
    OPERATIONAL = "operational"  # Operational alerts (e.g., "First call missed")


class SignalSeverity(str, enum.Enum):
    """Signal severity level."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class KeySignal(Base):
    """
    Automatic alerts and signals generated by Otto/Shunya.
    
    Examples:
    - "Rep late to appointment"
    - "Customer showing urgent intent"
    - "First call missed"
    - "High likelihood of closing"
    """
    __tablename__ = "key_signals"
    __table_args__ = (
        Index("ix_signals_contact_card", "contact_card_id"),
        Index("ix_signals_lead", "lead_id"),
        Index("ix_signals_appointment", "appointment_id"),
        Index("ix_signals_type_severity", "signal_type", "severity"),
        Index("ix_signals_created", "created_at"),
        Index("ix_signals_unique_key", "unique_key", "company_id"),  # For idempotency checks
    )

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    company_id = Column(String, ForeignKey("companies.id"), nullable=False, index=True)
    
    # Foreign keys
    contact_card_id = Column(String, ForeignKey("contact_cards.id"), nullable=False, index=True)
    lead_id = Column(String, ForeignKey("leads.id"), nullable=True, index=True)
    appointment_id = Column(String, ForeignKey("appointments.id"), nullable=True, index=True)
    
    # Signal details
    signal_type = Column(
        Enum(SignalType, native_enum=False, name="signal_type"),
        nullable=False,
        index=True,
    )
    severity = Column(
        Enum(SignalSeverity, native_enum=False, name="signal_severity"),
        nullable=False,
        default=SignalSeverity.MEDIUM,
    )
    title = Column(String, nullable=False, comment="Signal title (e.g., 'Rep late to appointment')")
    description = Column(Text, nullable=True, comment="Detailed signal description")
    
    # Idempotency: natural key for duplicate detection
    unique_key = Column(String, nullable=True, index=True, comment="Hash of (signal_type, title, contact_card_id) for duplicate detection")
    
    # Metadata
    signal_metadata = Column(JSON, nullable=True, comment="Additional signal context")
    acknowledged = Column(Boolean, default=False, comment="Whether signal has been acknowledged")
    acknowledged_at = Column(DateTime, nullable=True)
    acknowledged_by = Column(String, nullable=True, comment="User ID who acknowledged")
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    contact_card = relationship("ContactCard", back_populates="key_signals")
    lead = relationship("Lead", back_populates="key_signals")
    appointment = relationship("Appointment", back_populates="key_signals")
    company = relationship("Company", foreign_keys=[company_id])

